### ISSUE TITLE
Ошибка при открытии ключа реестра

### ISSUE THREAD

**Issue by filya1992** [xvitaly/srcrepair#102]
SRC Repair version (версия SRC Repair): 30.0.2.5296
Windows version (версия Windows):  10

Problem details (подробно опишите возникшую проблему):
При запуске программы выдает ошибку:
![m4fbk5vbrva](https://user-images.githubusercontent.com/35102376/34563976-fc1fbca0-f165-11e7-88f6-19fccfd2ff2d.jpg)
![ffyhng1ovpi](https://user-images.githubusercontent.com/35102376/34563990-0f895904-f166-11e7-8297-02258e7b133b.jpg)

**Comment by xvitaly** [comment]
Запустите хотя бы один раз данную игру (Team Fortress 2).

**Comment by filya1992** [comment]
Не помогает это!
Еще один момент: установщик не дает установить программу куда я хочу, устанавливает только в c:Users/appdata/...

**Comment by filya1992** [comment]
Пару дней назад всё было нормально. Видимо до последнего обновления.

**Comment by xvitaly** [comment]
> Пару дней назад всё было нормально. Видимо до последнего обновления.

Хорошо, сегодня проверим это.

**Comment by xvitaly** [comment]
> Пару дней назад всё было нормально. Видимо до последнего обновления.

Мы проверили работу SRC Repair на свежеустановленной ОС Windows 10 (1709, RS3) с чисто установленным Steam и TF2 последних версий - всё работает успешно. Настройки загружаются и сохраняются без проблем:

![2](https://user-images.githubusercontent.com/966711/34568673-65459444-f188-11e7-8bec-15696b79b985.png)

Вы запускаете программу под тем же пользователем, что и игру? Игру и Steam, надеюсь, не запускаете с правами администратора случайно?

Попробуйте открыть редактор реестра (**Пуск** - **Выполнить** - `regedit.exe`), перейти в ветку `HKEY_CURRENT_USER\Software\Valve\Source\tf\Settings` и проверить есть ли там настройки графики игры:

![3](https://user-images.githubusercontent.com/966711/34568692-72ab85b2-f188-11e7-88b9-095135f6dcf5.png)

>  Еще один момент: установщик не дает установить программу куда я хочу, устанавливает только в c:Users/appdata/...

Также не подтверждаем. Мы проверили - всё работает отлично. Путь меняется посредством нажатия кнопки **Обзор**:

![1](https://user-images.githubusercontent.com/966711/34568846-e099241c-f188-11e7-803e-d85f924406df.png)

**Comment by filya1992** [comment]
Ну в чем проблем тогда?
Стим переустанавливал вчера.
Вот что пишет при установке:
![lqtd2zuvi9y](https://user-images.githubusercontent.com/35102376/34591230-253bf36c-f1cd-11e7-885b-d2605ac0d429.jpg)
![zm6sk3zo6ac](https://user-images.githubusercontent.com/35102376/34591237-307fe2b0-f1cd-11e7-933e-7bb4321b8bc5.jpg)
![zn2yfnbvfdy](https://user-images.githubusercontent.com/35102376/34591254-433cb0ae-f1cd-11e7-94c8-ee4378ddab5a.jpg)
Вот версия ОС:
![kp9y6e6_eoq](https://user-images.githubusercontent.com/35102376/34591280-5d2c16d0-f1cd-11e7-83b5-03da67aeea6c.jpg)
Вот что в реестре:
![5egnmej4r14](https://user-images.githubusercontent.com/35102376/34591302-7742dacc-f1cd-11e7-8b92-e452e1f94745.jpg)

**Comment by xvitaly** [comment]
>  Вот что пишет при установке:

**Comment by filya1992** [comment]
всё, разобрался. Спасибо за помощь

**Comment by xvitaly** [comment]
> всё, разобрался. Спасибо за помощь

Проблема решена? Всё работает?

**Comment by filya1992** [comment]
Да всё в норме. Нужно было 1 раз запустить тф без параметров запуска. После этого настройки сразу загрузились.
По поводу установки прог-мы: запустил с правами админа - всё сразу установилось.
Еще раз благодарю
