### ISSUE TITLE
Произошла ошибка при открытии ключа реестра

### ISSUE THREAD

**Issue by Marise97** [xvitaly/srcrepair#111]
SRC Repair version (версия SRC Repair): 31.0.0.6000
Windows version (версия Windows): Windows 10 Pro 1709 (16299.214)

Problem details (подробно опишите возникшую проблему):
При открытии программы она сперва показывает диалоговое окно с ошибкой "Произошла ошибка при открытии ключа реестра. Графические настройки не были загружены!"
Далее открывается программа с одной лишь игрой CS:S собственно только она у меня и установлена.
Настроек нет, все поля пусты.

P.S. так же сами настройки не хотят сохраняться после изменений именно в самой игре (мб это как-то связано) увы как исправить эту проблему я не знаю.
Заранее Спасибо!

**Comment by xvitaly** [comment]
>  Далее открывается программа с одной лишь игрой CS:S собственно только она у меня и установлена.

1. Игра лицензия?
2. Запустите данную игру хотя бы один раз.

**Comment by Marise97** [comment]
> Игра лицензия?
Запустите данную игру хотя бы один раз.

Запускал и не один раз.
Конечно лицензия.

**Comment by xvitaly** [comment]
> Запускал и не один раз.

Выложите сюда содержимое файла `%APPDATA%\SRC Repair\debug.log` для анализа.

**Comment by xvitaly** [comment]
Также обязательно проверьте [описанное здесь решение](https://github.com/xvitaly/srcrepair/issues/102#issuecomment-355553420). Скорее всего, проблема в наличии параметра запуска. Он же и блокирует возможность сохранения настроек игры.
