### ISSUE TITLE
Problem with Garry's Mod and DirectX 8.x

### ISSUE THREAD

**Issue by ideall2** [xvitaly/srcrepair#112]
SRC Repair version (версия SRC Repair): 31.0.0.6000
Windows version (версия Windows): 10.                                                                                                        
[mapcycle.txt](https://github.com/xvitaly/srcrepair/files/1751592/mapcycle.txt)

I have in Garry's mod does not change the settings

**Comment by xvitaly** [comment]
> I have in Garry's mod does not change the settings

Right click on Garry's Mod in Steam -> **Properties** -> press **Set launch options button** -> **clear all** -> press **OK** -> start game and close it. Now SRC Repair will work fine with this game.

**Comment by ideall2** [comment]
not help

**Comment by xvitaly** [comment]
> not help

After removing game launch options and launching game, restart SRC Repair.

**Comment by ideall2** [comment]
Not
help

**Comment by xvitaly** [comment]
Then please upload `%APPDATA%\SRC Repair\debug.log` file.

**Comment by ideall2** [comment]
I try to install dx8 but does not work, and other ways do not help, only the only way, but does not show materials

**Comment by xvitaly** [comment]
> I try to install dx8 but does not work

Maybe Garry's Mod don't support DirectX 8 anymore?

**Comment by ideall2** [comment]
That's possible.

**Comment by ideall2** [comment]
I'll try it another way.

**Comment by ideall2** [comment]
I'll have to do it the other way I found it.

**Comment by ideall2** [comment]
To change game settings under config

**Comment by ideall2** [comment]
Readily. Turn out
