### ISSUE TITLE
Проблема

### ISSUE THREAD

**Issue by ideall2** [xvitaly/srcrepair#114]
SRC Repair version (версия SRC Repair): Последняя
Windows version (версия Windows): 10

Problem details (подробно опишите возникшую проблему):
 У меня такая проблема; в некоторые играх не могут меняться настройки через SRC, сразу появляется ошибка. Произошла ошибка при открытие ключа реестра.
Графические настройки не были загружены

**Comment by ideall2** [comment]
В Garry s mod

**Comment by xvitaly** [comment]
https://github.com/xvitaly/srcrepair/issues/102#issuecomment-355553420

**Comment by ideall2** [comment]
Исправил за исключение одной проблемы

**Comment by ideall2** [comment]
С drx

**Comment by ideall2** [comment]
У меня не устанавливается directx 80

**Comment by xvitaly** [comment]
> У меня не устанавливается directx 80

Обсуждалось же уже в другом тикете. Игра его не поддерживает вообще.
