### ISSUE TITLE
Нет глаз у персонажей

### ISSUE THREAD

**Issue by anty78** [xvitaly/srcrepair#128]
Когда я выбираю конфиг и устанавливаю и запускаю tf2 то у пресонажей нет глаз исправте плиз

**Comment by xvitaly** [comment]
1. Лицевая анимация потребляет очень много ресурсов, поэтому все FPS конфиги её полностью отключают.
2. Все конфиги из поставки SRC Repair поставляются по лицензии "как есть", т.е. мы не имеем права вносить в них каких-либо изменений.
3. Снова включить лицевую анимацию можно если изменить значение `r_eyes 0` на `r_eyes 1`.

**Comment by anty78** [comment]
Ухты большое спасибо, теперь нормально сыграю на минималках с глазами.
