### ISSUE TITLE
Improve distribution of third-party configs

### ISSUE THREAD

**Issue by mastercoms** [xvitaly/srcrepair#373]
Hello! It was brought to my attention that this software is distributing a very old version of mastercomfig. I suggest that you instead use a system where configs are handled different based on if they are a cfg or VPK file, and install them to the correct directory accordingly.

With this, you can use the official download links, which always point to the latest version: https://github.com/mastercomfig/mastercomfig/releases/latest/download/mastercomfig-ultra-preset.vpk, as found on the [official download page](https://mastercomfig.com/download), instead of using a mirror.

I would also like to inform you that at the moment, your current distribution method is violating the MIT License that mastercomfig is licensed under. Namely, "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

Please resolve this issue as soon as possible. Thank you!

**Comment by xvitaly** [comment]
> I suggest that you instead use a system where configs are handled different based on if they are a cfg or VPK file, and install them to the correct directory accordingly.

SRC Repair support all Source Engine 1 games, not only TF2, that's why we use unpacked versions. The installations methods varies between Source Engine versions.

> With this, you can use the official download links, which always point to the latest version: https://github.com/mastercomfig/mastercomfig/releases/latest/download/mastercomfig-ultra-preset.vpk, as found on the official download page, instead of using a mirror.

Can you provide also releases in a simple Zip archives? We will use them without rewriting our application.

> I would also like to inform you that at the moment, your current distribution method is violating the MIT License that mastercomfig is licensed under. Namely, "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

Thanks. We will add a copy of MIT license to the distribution archive.

**Comment by xvitaly** [comment]
I will investigate if legacy Source Engine versions like Portal/L4D1 can use configs from VPK file.

**Comment by mastercoms** [comment]
Hi, thank you for your response and clarification. I can provide different distribution packages, including ZIP, for compatibility with these games.

**Comment by xvitaly** [comment]
> I can provide different distribution packages, including ZIP, for compatibility with these games. Please let me know what they require, and I can prepare the necessary files.

Great. Thank you for your hard work on FPS-configs. It would be great if you can create a version in a single `autoexec.cfg` file for the legacy Source Engine games (without TF2 binds).

SRC Repair support Zip archives with such structure:
`cfg/autoexec.cfg`

**Comment by xvitaly** [comment]
Updated our generator to create a single `autoexec.cfg` file.

It will include the following contents:
* `presets/low.cfg`
* `comfig/comfig.cfg`
* `comfig/finalize.cfg`
* a copy of LICENSE file.

Looks like it works fine.

**Comment by mastercoms** [comment]
Nice work! Thank you for your speedy solution of this matter. To give some feedback, it seems like mastercomfigpf's README.txt should have `Preset name: low` (right now it says ultra) and mastercomfigmq's README.txt should have `Preset name: ultra` (right now it says very-low). Also, you should include the following in the autoexec.cfg:

- `comfig/comfig.cfg`
- `presets/{low,ultra}.cfg`
- `comfig/modules_run.cfg`
- `comfig/finalize.cfg`

`comfig/modules_run.cfg` will actually apply the cvars within the module aliases.

**Comment by xvitaly** [comment]
Thanks for suggestion. Updated our [Bash script](https://github.com/EasyCoding/tf2cfgs/blob/master/assets/mastercomfig.sh) to include `comfig/modules_run.cfg`. Also fixed README files.

**Comment by mastercoms** [comment]
Awesome, thanks for your collaboration and prompt work!
