### ISSUE TITLE
Ошибка при открытии Dota 2 beta в программе SRC Repair

### ISSUE THREAD

**Issue by Sanzhik** [xvitaly/srcrepair#38]
SRC Repair version (версия SRC Repair): 
Windows version (версия Windows): 

Problem details (подробно опишите возникшую проблему):
Когда в программе я открываю игру Dota 2 beta мне выдает ошибку в которой написано
"Произошла ошибка при запуске графических настроек игры. Часть параметров загрузились некорректно" 
Что мне делать с возникшей проблемой?

**Comment by xvitaly** [comment]
Dota 2 не поддерживается в настоящее время. #10
