### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FeLTiz** [xvitaly/srcrepair#383]
SRC Repair version: 
Platform: 
Windows (or other OS) version: 10

Problem details:

![загруженное](https://user-images.githubusercontent.com/68109808/87149069-3d832f80-c2b8-11ea-9a34-5d73cae6fd87.png)

**Comment by xvitaly** [comment]
Нужно убрать в параметрах запуска данной игры `-autoconfig` и всё остальное, что там прописано.

Правой кнопкой по игре в Steam - Свойства - Установить параметры запуска - очистить поле ввода - нажать OK.
