### ISSUE TITLE
Ошибка при запуске.

### ISSUE THREAD

**Issue by JerryLegend** [xvitaly/srcrepair#40]
SRC Repair version (версия SRC Repair): 280 final
Windows version (версия Windows):  7(x64)

Problem details (подробно опишите возникшую проблему): При запуске выдает ошибку
http://imgur.com/a/94rkL

**Comment by xvitaly** [comment]
> При запуске выдает ошибку

1. Какие из поддерживаемых игр установлены?
2. Приложите файл `%APPDATA%\SRC Repair\debug.log`.

**Comment by JerryLegend** [comment]
Vitaly Zaitsev, помогите...
Дота2
http://imgur.com/a/XpHLq

**Comment by xvitaly** [comment]
> Дота2
Dota 2 пока ещё не поддерживается программой. То, что раньше она отображалась в списке, было ошибкой и это исправлено в последней версии программы и базы данных.

**Comment by xvitaly** [comment]
Если вам очень хочется, то можно снова вернуть Dota 2 в список игр, отрыв файл `games.xml` в текстовом редакторе и заменив в нём строку `<Enabled>0</Enabled>` на `<Enabled>1</Enabled>`. При следующем запуске SRC Repair увидит данную игру (как было в предыдущих версиях).

**Comment by JerryLegend** [comment]
Vitaly Zaitsev, я очень благодарен вам за помощь. Спасибо!
