### ISSUE TITLE
"Failed to load several graphical settings."

### ISSUE THREAD

**Issue by tgp1994** [xvitaly/srcrepair#81]
SRC Repair version: 29.0.0.5222
Windows version): 10 64bit v.1709

Problem details: After fresh-installing this application and starting it, a message box pops up with the message "Failed to load several graphical settings. Please report this bug."

So, uh, here's your bug report. No other information was provided to me.

**Comment by xvitaly** [comment]
Dota 2 game?

**Comment by tgp1994** [comment]
Actually, I think this was for Alien Swam. I didn't pay much attention to
the first game that was loaded, but it must be that game.

**Comment by xvitaly** [comment]
> Actually, I think this was for Alien Swam. I didn't pay much attention to

OK, I will check this later today.

**Comment by xvitaly** [comment]
Fixed by b396662fc3de477ab91bf4b5d3f7256cf7d95f3c. You can now try latest development snapshot from our [build system](https://ci.appveyor.com/project/xvitaly/srcrepair/build/artifacts).
