### ISSUE TITLE
"Select config file to edit" dialog too small

### ISSUE THREAD

**Issue by tgp1994** [xvitaly/srcrepair#82]
**SRC Repair version:** 29.0.0.5222
**Windows version):** 10 64bit v.1709

**Problem details:** I noticed a mysterious exclamation mark in the program after opening it and selecting Team Fortress 2. Upon clicking it, a _Select config file to edit_ dialog box opened asking me to chose a config. However, the path was too long to be displayed correctly, whether the drop down was "dropped" or not. (See images)

Ideas: Perhaps the box could be automatically expanded, or the path string could be shortened so its root is in whatever game we're editing?

![small1](https://user-images.githubusercontent.com/842942/32419604-549e5ab2-c231-11e7-9093-fff8598e9e3e.PNG)
![small2](https://user-images.githubusercontent.com/842942/32419607-5757ccf2-c231-11e7-8b1d-8a1ba74c985d.PNG)

**Comment by xvitaly** [comment]
Thanks for report. I will fix this in next version.

**Comment by xvitaly** [comment]
We added tooltip with full path.

**Comment by tgp1994** [comment]
Thank you!
