### ISSUE TITLE
Failed to load several graphical settings.

### ISSUE THREAD

**Issue by Astolpho69** [xvitaly/srcrepair#84]
SRC Repair version (29.0.0.5222)
Windows version (7 ultimate 64x)

Problem details 
![default](https://user-images.githubusercontent.com/33511942/32596124-43fa5cbe-c543-11e7-8618-3c1b4265e817.png)

When im trying to load src repair im pop up with the error. Game is Csgo
Когда я запускаю программу мне выдает ошибку, Игра Ксго. 

I tried to run it has admin so nothing happens. Road to game files clearly on eng.

Решение если можно то на Русском .

**Comment by xvitaly** [comment]
Благодарю за сообщение. Ошибка найдена и будет исправлена в ближайшее время.

**Comment by xvitaly** [comment]
Проблема решена. Вы можете загрузить последнюю тестовую версию для разработчиков [отсюда](https://ci.appveyor.com/project/xvitaly/srcrepair/build/artifacts).
